name: "Promote Model"
description: "Promote models from staging to 'ACTIVE', backing up the currently 'ACTIVE' models."

inputs:
  type:
    description: "The model type to promote. Must be 'issues' or 'pulls'."
    required: true

  staged_key:
    description: "The suffix for the staged cache entries to promote. Defaults to 'staged'."
    required: false
    default: "staged"

  backup_key:
    description: "The suffix for the backup cache entries. Defaults to 'backup'."
    required: false
    default: "backup"

branding:
  color: "purple"
  icon: "arrow-up"

runs:
  using: "composite"
  steps:
    - name: "Validate Inputs"
      shell: bash
      run: |
        if [[ "${{ inputs.type }}" != "issues" && "${{ inputs.type }}" != "pulls" ]]; then
          echo "::error::'type' must be either 'issues' or 'pulls'. Value provided: '${{ inputs.type }}'."
          echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
          echo "\`type\` must be either 'issues' or 'pulls'." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

    - name: "Set Environment Variables"
      shell: bash
      run: |
        echo "CATEGORY_CACHE_PATH=labeler-cache/category-${{ inputs.type }}-model.zip" >> $GITHUB_ENV
        echo "SERVICE_CACHE_PATH=labeler-cache/service-${{ inputs.type }}-model.zip" >> $GITHUB_ENV
        echo "CATEGORY_STAGED_KEY=issue-labeler/model/category-${{ inputs.type }}/${{ inputs.staged_key || 'staged' }}" >> $GITHUB_ENV
        echo "SERVICE_STAGED_KEY=issue-labeler/model/service-${{ inputs.type }}/${{ inputs.staged_key || 'staged' }}" >> $GITHUB_ENV
        echo "CATEGORY_ACTIVE_KEY=issue-labeler/model/category-${{ inputs.type }}/ACTIVE" >> $GITHUB_ENV
        echo "SERVICE_ACTIVE_KEY=issue-labeler/model/service-${{ inputs.type }}/ACTIVE" >> $GITHUB_ENV
        echo "CATEGORY_BACKUP_KEY=issue-labeler/model/category-${{ inputs.type }}/${{ inputs.backup_key }}" >> $GITHUB_ENV
        echo "SERVICE_BACKUP_KEY=issue-labeler/model/service-${{ inputs.type }}/${{ inputs.backup_key }}" >> $GITHUB_ENV

    - name: "Check for Existing Staged Cache Entries"
      id: check-staged
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ${{ env.CATEGORY_CACHE_PATH }}
          ${{ env.SERVICE_CACHE_PATH }}
        key: ${{ env.CATEGORY_STAGED_KEY }}
        restore-keys: ${{ env.SERVICE_STAGED_KEY }}
        lookup-only: true
        fail-on-cache-miss: true

    - name: "Check for Existing Backup Cache Entries"
      if: ${{ steps.check-staged.outputs.cache-hit == 'true' }}
      id: check-backup
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ${{ env.CATEGORY_CACHE_PATH }}
          ${{ env.SERVICE_CACHE_PATH }}
        key: ${{ env.CATEGORY_BACKUP_KEY }}
        restore-keys: ${{ env.SERVICE_BACKUP_KEY }}
        lookup-only: true
        fail-on-cache-miss: false

    - name: "Restore Existing Active Cache Entries"
      if: ${{ steps.check-staged.outputs.cache-hit == 'true' }}
      id: check-active
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ${{ env.CATEGORY_CACHE_PATH }}
          ${{ env.SERVICE_CACHE_PATH }}
        key: ${{ env.CATEGORY_ACTIVE_KEY }}
        restore-keys: ${{ env.SERVICE_ACTIVE_KEY }}
        fail-on-cache-miss: false

    - name: "Abort if Backup Cache Entries Already Exist"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' && steps.check-backup.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        echo "::error::Backup cache keys already exist. Cannot proceed with promotion."
        echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
        echo "Backup cache keys already exist. Cannot proceed with promotion." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "> [!TIP]" >> $GITHUB_STEP_SUMMARY
        echo "> Either use a different \`backup_key\` value or delete the existing cache entries from the [Action Caches](/${{ github.repository }}/actions/caches) page and run the workflow again." >> $GITHUB_STEP_SUMMARY
        exit 1

    - name: "Cache Backup of Current Active Cache Entries"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' }}
      id: backup-category
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ env.CATEGORY_CACHE_PATH }}
        key: ${{ env.CATEGORY_BACKUP_KEY }}

    - name: "Cache Backup of Current Active Service Cache Entry"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' }}
      id: backup-service
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ env.SERVICE_CACHE_PATH }}
        key: ${{ env.SERVICE_BACKUP_KEY }}

    - name: "Remove Local Copies of Current Active Cache Entries"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        rm -f ${{ env.CATEGORY_CACHE_PATH }}
        rm -f ${{ env.SERVICE_CACHE_PATH }}

    - name: "Restore the Staged Cache Entries to Promote"
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ${{ env.CATEGORY_CACHE_PATH }}
          ${{ env.SERVICE_CACHE_PATH }}
        key: ${{ env.CATEGORY_STAGED_KEY }}
        restore-keys: ${{ env.SERVICE_STAGED_KEY }}
        fail-on-cache-miss: true

    - name: "Delete Existing Active Cache Entries"
      if: ${{ steps.check-active.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        gh cache delete "${{ env.CATEGORY_ACTIVE_KEY }}"
        gh cache delete "${{ env.SERVICE_ACTIVE_KEY }}"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: "Save the Staged Cache Entries as the ACTIVE Cache Entries"
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ env.CATEGORY_CACHE_PATH }}
        key: ${{ env.CATEGORY_ACTIVE_KEY }}

    - name: "Save the Staged Service Cache Entry as the ACTIVE Service Cache Entry"
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ env.SERVICE_CACHE_PATH }}
        key: ${{ env.SERVICE_ACTIVE_KEY }}

    - name: "Write Summary"
      shell: bash
      run: |
        echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
        echo "> The ${{ inputs.type == 'issues' && 'Issues' || 'Pull Requests' }} models were promoted from '${{ inputs.staged_key }}' to 'ACTIVE'." >> $GITHUB_STEP_SUMMARY

        if [[ "${{ steps.check-active.outputs.cache-hit }}" == "true" ]]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
          echo "> The previous 'ACTIVE' ${{ inputs.type == 'issues' && 'Issues' || 'Pull Requests' }} models were backed up as '${{ inputs.backup_key }}'." >> $GITHUB_STEP_SUMMARY
          echo "> If the previous models need to be restored, promote '${{ inputs.backup_key }}' and supply a different \`backup_key\`." >> $GITHUB_STEP_SUMMARY
        fi
